# Generated by Django 3.2.13 on 2022-06-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_p_hone_number',
            new_name='default_phone_number',
        ),
    ]
