# Generated by Django 3.2.13 on 2022-07-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_user'),
        ('products', '0006_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Reviews Section')),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to='profiles.UserProfile')),
            ],
        ),
    ]
